// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyOlxZoy1S68eFouCeFwzYTDIoKOU6Ao',
    appId: '1:201784662224:web:84958ac9601b1ed24226d5',
    messagingSenderId: '201784662224',
    projectId: 'flutternotes-28db3',
    authDomain: 'flutternotes-28db3.firebaseapp.com',
    storageBucket: 'flutternotes-28db3.firebasestorage.app',
    measurementId: 'G-EF3FGEDD9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86mBsvcfK-SZ1UpHCX0O3gH_57xZNQos',
    appId: '1:201784662224:android:ae148e8fa290c6014226d5',
    messagingSenderId: '201784662224',
    projectId: 'flutternotes-28db3',
    storageBucket: 'flutternotes-28db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuAnw4CfjQeZtNQSdxYPAWzk-goYRzm0',
    appId: '1:201784662224:ios:3784c0875471c5cf4226d5',
    messagingSenderId: '201784662224',
    projectId: 'flutternotes-28db3',
    storageBucket: 'flutternotes-28db3.firebasestorage.app',
    iosBundleId: 'com.example.flutternotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuAnw4CfjQeZtNQSdxYPAWzk-goYRzm0',
    appId: '1:201784662224:ios:3784c0875471c5cf4226d5',
    messagingSenderId: '201784662224',
    projectId: 'flutternotes-28db3',
    storageBucket: 'flutternotes-28db3.firebasestorage.app',
    iosBundleId: 'com.example.flutternotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyyOlxZoy1S68eFouCeFwzYTDIoKOU6Ao',
    appId: '1:201784662224:web:02517438f78a4f1f4226d5',
    messagingSenderId: '201784662224',
    projectId: 'flutternotes-28db3',
    authDomain: 'flutternotes-28db3.firebaseapp.com',
    storageBucket: 'flutternotes-28db3.firebasestorage.app',
    measurementId: 'G-3L10C0QHCY',
  );
}
